# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-24 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=55)),
                ('location', models.CharField(max_length=255)),
                ('s_or_c', models.CharField(max_length=55)),
                ('b_or_v', models.CharField(max_length=55)),
                ('prevailing', models.CharField(max_length=55)),
                ('hours', models.IntegerField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
