# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-25 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191024_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='company',
            field=models.CharField(default='No company listed', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
